name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: poria-dev
          theme: github-dark
          speed: 2
          output: svg

      - name: Push generated SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
